spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.106.109:5432/postgres?currentSchema=public
    username: postgres
    password: 123456
    hikari:
    pool-name: Hikari-Postgres
    maximum-pool-size: 15
    minimum-idle: 3
    auto-commit: false
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 5000
    connection-test-query: SELECT 1
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql 建议用日志级别控制，便于生产关闭
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false


server:
  port: 8081


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE